spring:
  datasource:
    url: jdbc:postgresql://filemanagement-db.cri22gkiskwr.ap-northeast-2.rds.amazonaws.com:5432/file-management
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: classpath:/static/, file:/tmp/uploads/
